### ISSUE TITLE
About font-size(s)

### ISSUE THREAD

**Issue by huy-qn** [jamiewilson/corpus#10]
This is exactly what I am trying to do for my projects but better and well organized. 

What do you think about adding classes for sizing text such as ".small-text, lg-text, etc". I was thinking that now we only have h1-h6 that is preferable used with heading but not ordinary texts. There are cases we want to use texts with 75% smaller size or 125% larger either for hints or attracting attention.

**Comment by jamiewilson** [comment]
yeah, I'm definitely open to replacing these with percentages instead, but you might be able to achieve what you need with: https://github.com/jamiewilson/corpus/blob/master/_typography.scss#L169-L182

**Comment by huy-qn** [comment]
Nice, actually I was finding this one! Thanks!
