### ISSUE TITLE
Styling/layout broken in Firefox.

### ISSUE THREAD

**Issue by ivavictoria** [jamiewilson/corpus#2]
The site looks great in Chrome, but in Firefox and IE11, things look very jumbled. :cyclone:
If you can't seem to reproduce the problem, let me know and I can post some screenshots.

**Comment by rosswaycaster** [comment]
I am seeing this too. I'd really like to start using this for my projects. Any idea how to assure it's compatible with all modern browsers?

Also could something like http://flexiejs.com/ be used to add support for ie?

**Comment by jamiewilson** [comment]
Hey @Aurif3x and @rosswaycaster would you guys mind checking firefox again. I made some changes and most everything should be resolved. And as far as supporting older versions of ie, this is might not be the best thing to use. I suggest using something like http://www.basscss.com/. 

Thanks for the help with this! let me know if you catch any thing else.

**Comment by ivavictoria** [comment]
All better! :smiley:

**Comment by jamiewilson** [comment]
thanks for taking a look!
