### ISSUE TITLE
structure

### ISSUE THREAD

**Issue by moklick** [jamiewilson/corpus#3]
Hey,

corpus seems to be very nice. Thanks for uploading it to Github :)

I think people could use it more easily if you would create folders like src/lib and build/dist.
So for example src for all the .scss files and a dist folder for a compiled and bundled .css file and a bundled .scss file.

Regards,

Moritz

**Comment by jamiewilson** [comment]
Thanks for the input @moklick. I'll certainly consider adding a compiled version of the code as well.

**Comment by rodymolenaar** [comment]
Maybe adding the docs to this repo is a possibility too?

**Comment by jamiewilson** [comment]
@rodymol123 @moklick Hey, thanks for the requests. i think I'll keep them separate for now and let people compile the .scss themselves. But I added a little explanation here if you're interested: https://github.com/jamiewilson/corpus/blob/master/README.md#docs

I'm totally open to changing this in the future, but this way seems to make the most sense to me right now.
