### ISSUE TITLE
remove variables reference file?

### ISSUE THREAD

**Issue by rickghome** [jamiewilson/corpus#6]
Suggest that you either commit to using variables.scss, or remove it. Other files have their own and it may conflict.

**Comment by jamiewilson** [comment]
Yeah. I've thought about that. I left the _variables file there as a reference file of all the variables used. I thought this might be helpful if you wanted to overwrite variables for your project. So, all you'd need to do is uncomment _variables.scss and change the values. 

Thanks for the feedback. I'll think about this idea.

**Comment by jamiewilson** [comment]
Yea, I think I'll keep it for now, but try to make it clearer why it's included. Thanks for the feedback!
