### ISSUE TITLE
compilation order matters...

### ISSUE THREAD

**Issue by rickghome** [jamiewilson/corpus#8]
You have a few dependencies (e.g. body definition), that are impacted by the order in which sass files are compiled. Suggest that you offer an aggregate sass file that imports your general sass files to avoid these issues.

**Comment by jamiewilson** [comment]
Good thought. just ran into this myself on a new project. Maybe a corpus.scss file with all the @imports?

**Comment by rickghome** [comment]
Here’s what I built…

//these came from the furtive project...

@import "bourbon";
@import "reset";
@import "colors";
@import "whitespace";
@import "breakpoints";
@import "typography";
@import "animation";
@import "borders";
@import "sizing";
@import "depth";
@import "buttons";
@import "forms";
@import “custom_overrides";
@import "grid";
@import "images";
@import "positioning";
@import "gojumixins";
@import "tables";
@import "utilities";

I also use a few of my own classes, like this:

@import "elements";
@import "menus";
@import "layout";

**Comment by jamiewilson** [comment]
Added this file here for reference. I'll try to put some better documentation out soon too. Thanks for the help on this!

https://github.com/jamiewilson/corpus/blob/master/corpus.scss
